version: '3.1'
services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    restart: always     # 开机自动重启
    privileged: true
    environment:
      TZ: Asia/Shanghai
    ports: # 端口号绑定（宿主机:容器内）
      - '80:80'
      - '443:443'
    volumes: # 目录映射（宿主机:容器内）
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./ca:/etc/nginx/ca
      - ./auth:/etc/nginx/auth
